name: xBank
main: xBank.Core
version: 2.9
authors: [Xemos,firetire]
commands:
  bank:
    description: Bank command
    usage: /bank <command>
  bankcp:
    description: Admin commands
    usage: /bankcp <command>
  hbank:
    description: Old bank command
    usage: /hbank <command>